# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import profinet_pb2 as profinet__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in profinet_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProfinetServiceStub(object):
    """(ваш package, если есть)

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamPayload = channel.stream_unary(
                '/ProfinetService/StreamPayload',
                request_serializer=profinet__pb2.PayloadRequest.SerializeToString,
                response_deserializer=profinet__pb2.PayloadResponse.FromString,
                _registered_method=True)


class ProfinetServiceServicer(object):
    """(ваш package, если есть)

    """

    def StreamPayload(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProfinetServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamPayload': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamPayload,
                    request_deserializer=profinet__pb2.PayloadRequest.FromString,
                    response_serializer=profinet__pb2.PayloadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ProfinetService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ProfinetService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProfinetService(object):
    """(ваш package, если есть)

    """

    @staticmethod
    def StreamPayload(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/ProfinetService/StreamPayload',
            profinet__pb2.PayloadRequest.SerializeToString,
            profinet__pb2.PayloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ProfinetControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartBrute = channel.unary_unary(
                '/ProfinetController/StartBrute',
                request_serializer=profinet__pb2.StartRequest.SerializeToString,
                response_deserializer=profinet__pb2.StartResponse.FromString,
                _registered_method=True)
        self.StopBrute = channel.unary_unary(
                '/ProfinetController/StopBrute',
                request_serializer=profinet__pb2.StopRequest.SerializeToString,
                response_deserializer=profinet__pb2.StopResponse.FromString,
                _registered_method=True)


class ProfinetControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartBrute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopBrute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProfinetControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartBrute': grpc.unary_unary_rpc_method_handler(
                    servicer.StartBrute,
                    request_deserializer=profinet__pb2.StartRequest.FromString,
                    response_serializer=profinet__pb2.StartResponse.SerializeToString,
            ),
            'StopBrute': grpc.unary_unary_rpc_method_handler(
                    servicer.StopBrute,
                    request_deserializer=profinet__pb2.StopRequest.FromString,
                    response_serializer=profinet__pb2.StopResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ProfinetController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ProfinetController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProfinetController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartBrute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ProfinetController/StartBrute',
            profinet__pb2.StartRequest.SerializeToString,
            profinet__pb2.StartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopBrute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ProfinetController/StopBrute',
            profinet__pb2.StopRequest.SerializeToString,
            profinet__pb2.StopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
