# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: profinet.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'profinet.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eprofinet.proto\"\x97\x01\n\x0cStartRequest\x12\x16\n\x0einterface_name\x18\x01 \x01(\t\x12\x13\n\x0btarget_name\x18\x02 \x01(\t\x12\x14\n\x0cmodule_ident\x18\x03 \x01(\x05\x12\x17\n\x0fsubmodule_ident\x18\x04 \x01(\x05\x12\x14\n\x0cinput_length\x18\x05 \x01(\x05\x12\x15\n\routput_length\x18\x06 \x01(\x05\"1\n\rStartResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\r\n\x0bStopRequest\"0\n\x0cStopResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"f\n\x0ePayloadRequest\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12\x15\n\rcycle_counter\x18\x02 \x01(\x05\x12\x13\n\x0b\x64\x61ta_status\x18\x03 \x01(\x05\x12\x17\n\x0ftransfer_status\x18\x04 \x01(\x05\"\"\n\x0fPayloadResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32G\n\x0fProfinetService\x12\x34\n\rStreamPayload\x12\x0f.PayloadRequest\x1a\x10.PayloadResponse(\x01\x32k\n\x12ProfinetController\x12+\n\nStartBrute\x12\r.StartRequest\x1a\x0e.StartResponse\x12(\n\tStopBrute\x12\x0c.StopRequest\x1a\r.StopResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'profinet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STARTREQUEST']._serialized_start=19
  _globals['_STARTREQUEST']._serialized_end=170
  _globals['_STARTRESPONSE']._serialized_start=172
  _globals['_STARTRESPONSE']._serialized_end=221
  _globals['_STOPREQUEST']._serialized_start=223
  _globals['_STOPREQUEST']._serialized_end=236
  _globals['_STOPRESPONSE']._serialized_start=238
  _globals['_STOPRESPONSE']._serialized_end=286
  _globals['_PAYLOADREQUEST']._serialized_start=288
  _globals['_PAYLOADREQUEST']._serialized_end=390
  _globals['_PAYLOADRESPONSE']._serialized_start=392
  _globals['_PAYLOADRESPONSE']._serialized_end=426
  _globals['_PROFINETSERVICE']._serialized_start=428
  _globals['_PROFINETSERVICE']._serialized_end=499
  _globals['_PROFINETCONTROLLER']._serialized_start=501
  _globals['_PROFINETCONTROLLER']._serialized_end=608
# @@protoc_insertion_point(module_scope)
