// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: profinet.proto
// Protobuf C++ Version: 6.33.4

#ifndef profinet_2eproto_2epb_2eh
#define profinet_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_profinet_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_profinet_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_profinet_2eproto;
}  // extern "C"
namespace profinet {
class IoUpdateResponse;
struct IoUpdateResponseDefaultTypeInternal;
extern IoUpdateResponseDefaultTypeInternal _IoUpdateResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull IoUpdateResponse_class_data_;
class IoWriteRequest;
struct IoWriteRequestDefaultTypeInternal;
extern IoWriteRequestDefaultTypeInternal _IoWriteRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull IoWriteRequest_class_data_;
class ModuleConfig;
struct ModuleConfigDefaultTypeInternal;
extern ModuleConfigDefaultTypeInternal _ModuleConfig_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ModuleConfig_class_data_;
class StartRequest;
struct StartRequestDefaultTypeInternal;
extern StartRequestDefaultTypeInternal _StartRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull StartRequest_class_data_;
class StartResponse;
struct StartResponseDefaultTypeInternal;
extern StartResponseDefaultTypeInternal _StartResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull StartResponse_class_data_;
class StopRequest;
struct StopRequestDefaultTypeInternal;
extern StopRequestDefaultTypeInternal _StopRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull StopRequest_class_data_;
class StopResponse;
struct StopResponseDefaultTypeInternal;
extern StopResponseDefaultTypeInternal _StopResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull StopResponse_class_data_;
}  // namespace profinet
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace profinet {

// ===================================================================


// -------------------------------------------------------------------

class StopResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:profinet.StopResponse) */ {
 public:
  inline StopResponse() : StopResponse(nullptr) {}
  ~StopResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(StopResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(StopResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR StopResponse(::google::protobuf::internal::ConstantInitialized);

  inline StopResponse(const StopResponse& from) : StopResponse(nullptr, from) {}
  inline StopResponse(StopResponse&& from) noexcept
      : StopResponse(nullptr, ::std::move(from)) {}
  inline StopResponse& operator=(const StopResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline StopResponse& operator=(StopResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StopResponse& default_instance() {
    return *reinterpret_cast<const StopResponse*>(
        &_StopResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(StopResponse& a, StopResponse& b) { a.Swap(&b); }
  inline void Swap(StopResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StopResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StopResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<StopResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const StopResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const StopResponse& from) { StopResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(StopResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "profinet.StopResponse"; }

  explicit StopResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  StopResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const StopResponse& from);
  StopResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, StopResponse&& from) noexcept
      : StopResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSuccessFieldNumber = 1,
  };
  // bool success = 1;
  void clear_success() ;
  bool success() const;
  void set_success(bool value);

  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);

  public:
  // @@protoc_insertion_point(class_scope:profinet.StopResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const StopResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    bool success_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_profinet_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull StopResponse_class_data_;
// -------------------------------------------------------------------

class StopRequest final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:profinet.StopRequest) */ {
 public:
  inline StopRequest() : StopRequest(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(StopRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(StopRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR StopRequest(::google::protobuf::internal::ConstantInitialized);

  inline StopRequest(const StopRequest& from) : StopRequest(nullptr, from) {}
  inline StopRequest(StopRequest&& from) noexcept
      : StopRequest(nullptr, ::std::move(from)) {}
  inline StopRequest& operator=(const StopRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline StopRequest& operator=(StopRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StopRequest& default_instance() {
    return *reinterpret_cast<const StopRequest*>(
        &_StopRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(StopRequest& a, StopRequest& b) { a.Swap(&b); }
  inline void Swap(StopRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StopRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StopRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<StopRequest>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const StopRequest& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const StopRequest& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "profinet.StopRequest"; }

  explicit StopRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  StopRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const StopRequest& from);
  StopRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, StopRequest&& from) noexcept
      : StopRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:profinet.StopRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 0,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  friend struct ::TableStruct_profinet_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull StopRequest_class_data_;
// -------------------------------------------------------------------

class StartResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:profinet.StartResponse) */ {
 public:
  inline StartResponse() : StartResponse(nullptr) {}
  ~StartResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(StartResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(StartResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR StartResponse(::google::protobuf::internal::ConstantInitialized);

  inline StartResponse(const StartResponse& from) : StartResponse(nullptr, from) {}
  inline StartResponse(StartResponse&& from) noexcept
      : StartResponse(nullptr, ::std::move(from)) {}
  inline StartResponse& operator=(const StartResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline StartResponse& operator=(StartResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StartResponse& default_instance() {
    return *reinterpret_cast<const StartResponse*>(
        &_StartResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(StartResponse& a, StartResponse& b) { a.Swap(&b); }
  inline void Swap(StartResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StartResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StartResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<StartResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const StartResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const StartResponse& from) { StartResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(StartResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "profinet.StartResponse"; }

  explicit StartResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  StartResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const StartResponse& from);
  StartResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, StartResponse&& from) noexcept
      : StartResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kErrorMessageFieldNumber = 2,
    kSuccessFieldNumber = 1,
  };
  // string error_message = 2;
  void clear_error_message() ;
  const ::std::string& error_message() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_error_message(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_error_message();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_error_message();
  void set_allocated_error_message(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_error_message() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_error_message(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_error_message();

  public:
  // bool success = 1;
  void clear_success() ;
  bool success() const;
  void set_success(bool value);

  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);

  public:
  // @@protoc_insertion_point(class_scope:profinet.StartResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 44,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const StartResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr error_message_;
    bool success_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_profinet_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull StartResponse_class_data_;
// -------------------------------------------------------------------

class ModuleConfig final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:profinet.ModuleConfig) */ {
 public:
  inline ModuleConfig() : ModuleConfig(nullptr) {}
  ~ModuleConfig() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ModuleConfig* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ModuleConfig));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ModuleConfig(::google::protobuf::internal::ConstantInitialized);

  inline ModuleConfig(const ModuleConfig& from) : ModuleConfig(nullptr, from) {}
  inline ModuleConfig(ModuleConfig&& from) noexcept
      : ModuleConfig(nullptr, ::std::move(from)) {}
  inline ModuleConfig& operator=(const ModuleConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline ModuleConfig& operator=(ModuleConfig&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ModuleConfig& default_instance() {
    return *reinterpret_cast<const ModuleConfig*>(
        &_ModuleConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ModuleConfig& a, ModuleConfig& b) { a.Swap(&b); }
  inline void Swap(ModuleConfig* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ModuleConfig* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ModuleConfig* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ModuleConfig>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ModuleConfig& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ModuleConfig& from) { ModuleConfig::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ModuleConfig* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "profinet.ModuleConfig"; }

  explicit ModuleConfig(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ModuleConfig(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ModuleConfig& from);
  ModuleConfig(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ModuleConfig&& from) noexcept
      : ModuleConfig(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSlotNumberFieldNumber = 1,
    kSubslotNumberFieldNumber = 2,
    kModuleIdentFieldNumber = 3,
    kSubmoduleIdentFieldNumber = 4,
    kInputLengthFieldNumber = 5,
    kOutputLengthFieldNumber = 6,
  };
  // int32 slot_number = 1;
  void clear_slot_number() ;
  ::int32_t slot_number() const;
  void set_slot_number(::int32_t value);

  private:
  ::int32_t _internal_slot_number() const;
  void _internal_set_slot_number(::int32_t value);

  public:
  // int32 subslot_number = 2;
  void clear_subslot_number() ;
  ::int32_t subslot_number() const;
  void set_subslot_number(::int32_t value);

  private:
  ::int32_t _internal_subslot_number() const;
  void _internal_set_subslot_number(::int32_t value);

  public:
  // uint32 module_ident = 3;
  void clear_module_ident() ;
  ::uint32_t module_ident() const;
  void set_module_ident(::uint32_t value);

  private:
  ::uint32_t _internal_module_ident() const;
  void _internal_set_module_ident(::uint32_t value);

  public:
  // uint32 submodule_ident = 4;
  void clear_submodule_ident() ;
  ::uint32_t submodule_ident() const;
  void set_submodule_ident(::uint32_t value);

  private:
  ::uint32_t _internal_submodule_ident() const;
  void _internal_set_submodule_ident(::uint32_t value);

  public:
  // int32 input_length = 5;
  void clear_input_length() ;
  ::int32_t input_length() const;
  void set_input_length(::int32_t value);

  private:
  ::int32_t _internal_input_length() const;
  void _internal_set_input_length(::int32_t value);

  public:
  // int32 output_length = 6;
  void clear_output_length() ;
  ::int32_t output_length() const;
  void set_output_length(::int32_t value);

  private:
  ::int32_t _internal_output_length() const;
  void _internal_set_output_length(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:profinet.ModuleConfig)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 6,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ModuleConfig& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t slot_number_;
    ::int32_t subslot_number_;
    ::uint32_t module_ident_;
    ::uint32_t submodule_ident_;
    ::int32_t input_length_;
    ::int32_t output_length_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_profinet_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ModuleConfig_class_data_;
// -------------------------------------------------------------------

class IoWriteRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:profinet.IoWriteRequest) */ {
 public:
  inline IoWriteRequest() : IoWriteRequest(nullptr) {}
  ~IoWriteRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(IoWriteRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(IoWriteRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR IoWriteRequest(::google::protobuf::internal::ConstantInitialized);

  inline IoWriteRequest(const IoWriteRequest& from) : IoWriteRequest(nullptr, from) {}
  inline IoWriteRequest(IoWriteRequest&& from) noexcept
      : IoWriteRequest(nullptr, ::std::move(from)) {}
  inline IoWriteRequest& operator=(const IoWriteRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline IoWriteRequest& operator=(IoWriteRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const IoWriteRequest& default_instance() {
    return *reinterpret_cast<const IoWriteRequest*>(
        &_IoWriteRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(IoWriteRequest& a, IoWriteRequest& b) { a.Swap(&b); }
  inline void Swap(IoWriteRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IoWriteRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  IoWriteRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<IoWriteRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const IoWriteRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const IoWriteRequest& from) { IoWriteRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(IoWriteRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "profinet.IoWriteRequest"; }

  explicit IoWriteRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  IoWriteRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const IoWriteRequest& from);
  IoWriteRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, IoWriteRequest&& from) noexcept
      : IoWriteRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDataFieldNumber = 2,
    kOffsetFieldNumber = 1,
  };
  // bytes data = 2;
  void clear_data() ;
  const ::std::string& data() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_data(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_data();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_data();
  void set_allocated_data(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_data() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_data(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_data();

  public:
  // int32 offset = 1;
  void clear_offset() ;
  ::int32_t offset() const;
  void set_offset(::int32_t value);

  private:
  ::int32_t _internal_offset() const;
  void _internal_set_offset(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:profinet.IoWriteRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const IoWriteRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr data_;
    ::int32_t offset_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_profinet_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull IoWriteRequest_class_data_;
// -------------------------------------------------------------------

class IoUpdateResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:profinet.IoUpdateResponse) */ {
 public:
  inline IoUpdateResponse() : IoUpdateResponse(nullptr) {}
  ~IoUpdateResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(IoUpdateResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(IoUpdateResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR IoUpdateResponse(::google::protobuf::internal::ConstantInitialized);

  inline IoUpdateResponse(const IoUpdateResponse& from) : IoUpdateResponse(nullptr, from) {}
  inline IoUpdateResponse(IoUpdateResponse&& from) noexcept
      : IoUpdateResponse(nullptr, ::std::move(from)) {}
  inline IoUpdateResponse& operator=(const IoUpdateResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline IoUpdateResponse& operator=(IoUpdateResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const IoUpdateResponse& default_instance() {
    return *reinterpret_cast<const IoUpdateResponse*>(
        &_IoUpdateResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 6;
  friend void swap(IoUpdateResponse& a, IoUpdateResponse& b) { a.Swap(&b); }
  inline void Swap(IoUpdateResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IoUpdateResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  IoUpdateResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<IoUpdateResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const IoUpdateResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const IoUpdateResponse& from) { IoUpdateResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(IoUpdateResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "profinet.IoUpdateResponse"; }

  explicit IoUpdateResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  IoUpdateResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const IoUpdateResponse& from);
  IoUpdateResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, IoUpdateResponse&& from) noexcept
      : IoUpdateResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDataFieldNumber = 2,
    kOffsetFieldNumber = 1,
    kIsGoodQualityFieldNumber = 3,
  };
  // bytes data = 2;
  void clear_data() ;
  const ::std::string& data() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_data(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_data();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_data();
  void set_allocated_data(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_data() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_data(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_data();

  public:
  // int32 offset = 1;
  void clear_offset() ;
  ::int32_t offset() const;
  void set_offset(::int32_t value);

  private:
  ::int32_t _internal_offset() const;
  void _internal_set_offset(::int32_t value);

  public:
  // bool is_good_quality = 3;
  void clear_is_good_quality() ;
  bool is_good_quality() const;
  void set_is_good_quality(bool value);

  private:
  bool _internal_is_good_quality() const;
  void _internal_set_is_good_quality(bool value);

  public:
  // @@protoc_insertion_point(class_scope:profinet.IoUpdateResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const IoUpdateResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr data_;
    ::int32_t offset_;
    bool is_good_quality_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_profinet_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull IoUpdateResponse_class_data_;
// -------------------------------------------------------------------

class StartRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:profinet.StartRequest) */ {
 public:
  inline StartRequest() : StartRequest(nullptr) {}
  ~StartRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(StartRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(StartRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR StartRequest(::google::protobuf::internal::ConstantInitialized);

  inline StartRequest(const StartRequest& from) : StartRequest(nullptr, from) {}
  inline StartRequest(StartRequest&& from) noexcept
      : StartRequest(nullptr, ::std::move(from)) {}
  inline StartRequest& operator=(const StartRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline StartRequest& operator=(StartRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StartRequest& default_instance() {
    return *reinterpret_cast<const StartRequest*>(
        &_StartRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(StartRequest& a, StartRequest& b) { a.Swap(&b); }
  inline void Swap(StartRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StartRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StartRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<StartRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const StartRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const StartRequest& from) { StartRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(StartRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "profinet.StartRequest"; }

  explicit StartRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  StartRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const StartRequest& from);
  StartRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, StartRequest&& from) noexcept
      : StartRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kModulesFieldNumber = 5,
    kInterfaceNameFieldNumber = 1,
    kStationNameFieldNumber = 2,
    kVendorIdFieldNumber = 3,
    kDeviceIdFieldNumber = 4,
  };
  // repeated .profinet.ModuleConfig modules = 5;
  int modules_size() const;
  private:
  int _internal_modules_size() const;

  public:
  void clear_modules() ;
  ::profinet::ModuleConfig* PROTOBUF_NONNULL mutable_modules(int index);
  ::google::protobuf::RepeatedPtrField<::profinet::ModuleConfig>* PROTOBUF_NONNULL mutable_modules();

  private:
  const ::google::protobuf::RepeatedPtrField<::profinet::ModuleConfig>& _internal_modules() const;
  ::google::protobuf::RepeatedPtrField<::profinet::ModuleConfig>* PROTOBUF_NONNULL _internal_mutable_modules();
  public:
  const ::profinet::ModuleConfig& modules(int index) const;
  ::profinet::ModuleConfig* PROTOBUF_NONNULL add_modules();
  const ::google::protobuf::RepeatedPtrField<::profinet::ModuleConfig>& modules() const;
  // string interface_name = 1;
  void clear_interface_name() ;
  const ::std::string& interface_name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_interface_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_interface_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_interface_name();
  void set_allocated_interface_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_interface_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_interface_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_interface_name();

  public:
  // string station_name = 2;
  void clear_station_name() ;
  const ::std::string& station_name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_station_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_station_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_station_name();
  void set_allocated_station_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_station_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_station_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_station_name();

  public:
  // uint32 vendor_id = 3;
  void clear_vendor_id() ;
  ::uint32_t vendor_id() const;
  void set_vendor_id(::uint32_t value);

  private:
  ::uint32_t _internal_vendor_id() const;
  void _internal_set_vendor_id(::uint32_t value);

  public:
  // uint32 device_id = 4;
  void clear_device_id() ;
  ::uint32_t device_id() const;
  void set_device_id(::uint32_t value);

  private:
  ::uint32_t _internal_device_id() const;
  void _internal_set_device_id(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:profinet.StartRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   1, 56,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const StartRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::profinet::ModuleConfig > modules_;
    ::google::protobuf::internal::ArenaStringPtr interface_name_;
    ::google::protobuf::internal::ArenaStringPtr station_name_;
    ::uint32_t vendor_id_;
    ::uint32_t device_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_profinet_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull StartRequest_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ModuleConfig

// int32 slot_number = 1;
inline void ModuleConfig::clear_slot_number() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.slot_number_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::int32_t ModuleConfig::slot_number() const {
  // @@protoc_insertion_point(field_get:profinet.ModuleConfig.slot_number)
  return _internal_slot_number();
}
inline void ModuleConfig::set_slot_number(::int32_t value) {
  _internal_set_slot_number(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:profinet.ModuleConfig.slot_number)
}
inline ::int32_t ModuleConfig::_internal_slot_number() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.slot_number_;
}
inline void ModuleConfig::_internal_set_slot_number(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.slot_number_ = value;
}

// int32 subslot_number = 2;
inline void ModuleConfig::clear_subslot_number() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.subslot_number_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int32_t ModuleConfig::subslot_number() const {
  // @@protoc_insertion_point(field_get:profinet.ModuleConfig.subslot_number)
  return _internal_subslot_number();
}
inline void ModuleConfig::set_subslot_number(::int32_t value) {
  _internal_set_subslot_number(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:profinet.ModuleConfig.subslot_number)
}
inline ::int32_t ModuleConfig::_internal_subslot_number() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.subslot_number_;
}
inline void ModuleConfig::_internal_set_subslot_number(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.subslot_number_ = value;
}

// uint32 module_ident = 3;
inline void ModuleConfig::clear_module_ident() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.module_ident_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::uint32_t ModuleConfig::module_ident() const {
  // @@protoc_insertion_point(field_get:profinet.ModuleConfig.module_ident)
  return _internal_module_ident();
}
inline void ModuleConfig::set_module_ident(::uint32_t value) {
  _internal_set_module_ident(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:profinet.ModuleConfig.module_ident)
}
inline ::uint32_t ModuleConfig::_internal_module_ident() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.module_ident_;
}
inline void ModuleConfig::_internal_set_module_ident(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.module_ident_ = value;
}

// uint32 submodule_ident = 4;
inline void ModuleConfig::clear_submodule_ident() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.submodule_ident_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::uint32_t ModuleConfig::submodule_ident() const {
  // @@protoc_insertion_point(field_get:profinet.ModuleConfig.submodule_ident)
  return _internal_submodule_ident();
}
inline void ModuleConfig::set_submodule_ident(::uint32_t value) {
  _internal_set_submodule_ident(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:profinet.ModuleConfig.submodule_ident)
}
inline ::uint32_t ModuleConfig::_internal_submodule_ident() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.submodule_ident_;
}
inline void ModuleConfig::_internal_set_submodule_ident(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.submodule_ident_ = value;
}

// int32 input_length = 5;
inline void ModuleConfig::clear_input_length() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.input_length_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::int32_t ModuleConfig::input_length() const {
  // @@protoc_insertion_point(field_get:profinet.ModuleConfig.input_length)
  return _internal_input_length();
}
inline void ModuleConfig::set_input_length(::int32_t value) {
  _internal_set_input_length(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:profinet.ModuleConfig.input_length)
}
inline ::int32_t ModuleConfig::_internal_input_length() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.input_length_;
}
inline void ModuleConfig::_internal_set_input_length(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.input_length_ = value;
}

// int32 output_length = 6;
inline void ModuleConfig::clear_output_length() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.output_length_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::int32_t ModuleConfig::output_length() const {
  // @@protoc_insertion_point(field_get:profinet.ModuleConfig.output_length)
  return _internal_output_length();
}
inline void ModuleConfig::set_output_length(::int32_t value) {
  _internal_set_output_length(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:profinet.ModuleConfig.output_length)
}
inline ::int32_t ModuleConfig::_internal_output_length() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.output_length_;
}
inline void ModuleConfig::_internal_set_output_length(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.output_length_ = value;
}

// -------------------------------------------------------------------

// StartRequest

// string interface_name = 1;
inline void StartRequest::clear_interface_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.interface_name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& StartRequest::interface_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:profinet.StartRequest.interface_name)
  return _internal_interface_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void StartRequest::set_interface_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.interface_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:profinet.StartRequest.interface_name)
}
inline ::std::string* PROTOBUF_NONNULL StartRequest::mutable_interface_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_interface_name();
  // @@protoc_insertion_point(field_mutable:profinet.StartRequest.interface_name)
  return _s;
}
inline const ::std::string& StartRequest::_internal_interface_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.interface_name_.Get();
}
inline void StartRequest::_internal_set_interface_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.interface_name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL StartRequest::_internal_mutable_interface_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.interface_name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE StartRequest::release_interface_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:profinet.StartRequest.interface_name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.interface_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.interface_name_.Set("", GetArena());
  }
  return released;
}
inline void StartRequest::set_allocated_interface_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.interface_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.interface_name_.IsDefault()) {
    _impl_.interface_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:profinet.StartRequest.interface_name)
}

// string station_name = 2;
inline void StartRequest::clear_station_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.station_name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& StartRequest::station_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:profinet.StartRequest.station_name)
  return _internal_station_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void StartRequest::set_station_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.station_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:profinet.StartRequest.station_name)
}
inline ::std::string* PROTOBUF_NONNULL StartRequest::mutable_station_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_station_name();
  // @@protoc_insertion_point(field_mutable:profinet.StartRequest.station_name)
  return _s;
}
inline const ::std::string& StartRequest::_internal_station_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.station_name_.Get();
}
inline void StartRequest::_internal_set_station_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.station_name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL StartRequest::_internal_mutable_station_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.station_name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE StartRequest::release_station_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:profinet.StartRequest.station_name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.station_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.station_name_.Set("", GetArena());
  }
  return released;
}
inline void StartRequest::set_allocated_station_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.station_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.station_name_.IsDefault()) {
    _impl_.station_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:profinet.StartRequest.station_name)
}

// uint32 vendor_id = 3;
inline void StartRequest::clear_vendor_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.vendor_id_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::uint32_t StartRequest::vendor_id() const {
  // @@protoc_insertion_point(field_get:profinet.StartRequest.vendor_id)
  return _internal_vendor_id();
}
inline void StartRequest::set_vendor_id(::uint32_t value) {
  _internal_set_vendor_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:profinet.StartRequest.vendor_id)
}
inline ::uint32_t StartRequest::_internal_vendor_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.vendor_id_;
}
inline void StartRequest::_internal_set_vendor_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.vendor_id_ = value;
}

// uint32 device_id = 4;
inline void StartRequest::clear_device_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.device_id_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::uint32_t StartRequest::device_id() const {
  // @@protoc_insertion_point(field_get:profinet.StartRequest.device_id)
  return _internal_device_id();
}
inline void StartRequest::set_device_id(::uint32_t value) {
  _internal_set_device_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:profinet.StartRequest.device_id)
}
inline ::uint32_t StartRequest::_internal_device_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.device_id_;
}
inline void StartRequest::_internal_set_device_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.device_id_ = value;
}

// repeated .profinet.ModuleConfig modules = 5;
inline int StartRequest::_internal_modules_size() const {
  return _internal_modules().size();
}
inline int StartRequest::modules_size() const {
  return _internal_modules_size();
}
inline void StartRequest::clear_modules() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.modules_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::profinet::ModuleConfig* PROTOBUF_NONNULL StartRequest::mutable_modules(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:profinet.StartRequest.modules)
  return _internal_mutable_modules()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::profinet::ModuleConfig>* PROTOBUF_NONNULL StartRequest::mutable_modules()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:profinet.StartRequest.modules)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_modules();
}
inline const ::profinet::ModuleConfig& StartRequest::modules(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:profinet.StartRequest.modules)
  return _internal_modules().Get(index);
}
inline ::profinet::ModuleConfig* PROTOBUF_NONNULL StartRequest::add_modules()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::profinet::ModuleConfig* _add =
      _internal_mutable_modules()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:profinet.StartRequest.modules)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::profinet::ModuleConfig>& StartRequest::modules() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:profinet.StartRequest.modules)
  return _internal_modules();
}
inline const ::google::protobuf::RepeatedPtrField<::profinet::ModuleConfig>&
StartRequest::_internal_modules() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.modules_;
}
inline ::google::protobuf::RepeatedPtrField<::profinet::ModuleConfig>* PROTOBUF_NONNULL
StartRequest::_internal_mutable_modules() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.modules_;
}

// -------------------------------------------------------------------

// StartResponse

// bool success = 1;
inline void StartResponse::clear_success() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline bool StartResponse::success() const {
  // @@protoc_insertion_point(field_get:profinet.StartResponse.success)
  return _internal_success();
}
inline void StartResponse::set_success(bool value) {
  _internal_set_success(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:profinet.StartResponse.success)
}
inline bool StartResponse::_internal_success() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.success_;
}
inline void StartResponse::_internal_set_success(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = value;
}

// string error_message = 2;
inline void StartResponse::clear_error_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_message_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& StartResponse::error_message() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:profinet.StartResponse.error_message)
  return _internal_error_message();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void StartResponse::set_error_message(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.error_message_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:profinet.StartResponse.error_message)
}
inline ::std::string* PROTOBUF_NONNULL StartResponse::mutable_error_message()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_error_message();
  // @@protoc_insertion_point(field_mutable:profinet.StartResponse.error_message)
  return _s;
}
inline const ::std::string& StartResponse::_internal_error_message() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.error_message_.Get();
}
inline void StartResponse::_internal_set_error_message(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_message_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL StartResponse::_internal_mutable_error_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.error_message_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE StartResponse::release_error_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:profinet.StartResponse.error_message)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.error_message_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.error_message_.Set("", GetArena());
  }
  return released;
}
inline void StartResponse::set_allocated_error_message(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.error_message_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.error_message_.IsDefault()) {
    _impl_.error_message_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:profinet.StartResponse.error_message)
}

// -------------------------------------------------------------------

// StopRequest

// -------------------------------------------------------------------

// StopResponse

// bool success = 1;
inline void StopResponse::clear_success() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline bool StopResponse::success() const {
  // @@protoc_insertion_point(field_get:profinet.StopResponse.success)
  return _internal_success();
}
inline void StopResponse::set_success(bool value) {
  _internal_set_success(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:profinet.StopResponse.success)
}
inline bool StopResponse::_internal_success() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.success_;
}
inline void StopResponse::_internal_set_success(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = value;
}

// -------------------------------------------------------------------

// IoWriteRequest

// int32 offset = 1;
inline void IoWriteRequest::clear_offset() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.offset_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int32_t IoWriteRequest::offset() const {
  // @@protoc_insertion_point(field_get:profinet.IoWriteRequest.offset)
  return _internal_offset();
}
inline void IoWriteRequest::set_offset(::int32_t value) {
  _internal_set_offset(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:profinet.IoWriteRequest.offset)
}
inline ::int32_t IoWriteRequest::_internal_offset() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.offset_;
}
inline void IoWriteRequest::_internal_set_offset(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.offset_ = value;
}

// bytes data = 2;
inline void IoWriteRequest::clear_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& IoWriteRequest::data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:profinet.IoWriteRequest.data)
  return _internal_data();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void IoWriteRequest::set_data(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.data_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:profinet.IoWriteRequest.data)
}
inline ::std::string* PROTOBUF_NONNULL IoWriteRequest::mutable_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:profinet.IoWriteRequest.data)
  return _s;
}
inline const ::std::string& IoWriteRequest::_internal_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_.Get();
}
inline void IoWriteRequest::_internal_set_data(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL IoWriteRequest::_internal_mutable_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.data_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE IoWriteRequest::release_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:profinet.IoWriteRequest.data)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.data_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.data_.Set("", GetArena());
  }
  return released;
}
inline void IoWriteRequest::set_allocated_data(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.data_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:profinet.IoWriteRequest.data)
}

// -------------------------------------------------------------------

// IoUpdateResponse

// int32 offset = 1;
inline void IoUpdateResponse::clear_offset() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.offset_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int32_t IoUpdateResponse::offset() const {
  // @@protoc_insertion_point(field_get:profinet.IoUpdateResponse.offset)
  return _internal_offset();
}
inline void IoUpdateResponse::set_offset(::int32_t value) {
  _internal_set_offset(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:profinet.IoUpdateResponse.offset)
}
inline ::int32_t IoUpdateResponse::_internal_offset() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.offset_;
}
inline void IoUpdateResponse::_internal_set_offset(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.offset_ = value;
}

// bytes data = 2;
inline void IoUpdateResponse::clear_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& IoUpdateResponse::data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:profinet.IoUpdateResponse.data)
  return _internal_data();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void IoUpdateResponse::set_data(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.data_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:profinet.IoUpdateResponse.data)
}
inline ::std::string* PROTOBUF_NONNULL IoUpdateResponse::mutable_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:profinet.IoUpdateResponse.data)
  return _s;
}
inline const ::std::string& IoUpdateResponse::_internal_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_.Get();
}
inline void IoUpdateResponse::_internal_set_data(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL IoUpdateResponse::_internal_mutable_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.data_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE IoUpdateResponse::release_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:profinet.IoUpdateResponse.data)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.data_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.data_.Set("", GetArena());
  }
  return released;
}
inline void IoUpdateResponse::set_allocated_data(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.data_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:profinet.IoUpdateResponse.data)
}

// bool is_good_quality = 3;
inline void IoUpdateResponse::clear_is_good_quality() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_good_quality_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline bool IoUpdateResponse::is_good_quality() const {
  // @@protoc_insertion_point(field_get:profinet.IoUpdateResponse.is_good_quality)
  return _internal_is_good_quality();
}
inline void IoUpdateResponse::set_is_good_quality(bool value) {
  _internal_set_is_good_quality(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:profinet.IoUpdateResponse.is_good_quality)
}
inline bool IoUpdateResponse::_internal_is_good_quality() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.is_good_quality_;
}
inline void IoUpdateResponse::_internal_set_is_good_quality(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_good_quality_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace profinet


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // profinet_2eproto_2epb_2eh
