// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: profinet.proto

#include "profinet.pb.h"
#include "profinet.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace profinet {

static const char* ProfinetStackService_method_names[] = {
  "/profinet.ProfinetStackService/StartStack",
  "/profinet.ProfinetStackService/StopStack",
  "/profinet.ProfinetStackService/StreamIoData",
};

std::unique_ptr< ProfinetStackService::Stub> ProfinetStackService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ProfinetStackService::Stub> stub(new ProfinetStackService::Stub(channel, options));
  return stub;
}

ProfinetStackService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_StartStack_(ProfinetStackService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StopStack_(ProfinetStackService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StreamIoData_(ProfinetStackService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::Status ProfinetStackService::Stub::StartStack(::grpc::ClientContext* context, const ::profinet::StartRequest& request, ::profinet::StartResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::profinet::StartRequest, ::profinet::StartResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_StartStack_, context, request, response);
}

void ProfinetStackService::Stub::async::StartStack(::grpc::ClientContext* context, const ::profinet::StartRequest* request, ::profinet::StartResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::profinet::StartRequest, ::profinet::StartResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StartStack_, context, request, response, std::move(f));
}

void ProfinetStackService::Stub::async::StartStack(::grpc::ClientContext* context, const ::profinet::StartRequest* request, ::profinet::StartResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StartStack_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::profinet::StartResponse>* ProfinetStackService::Stub::PrepareAsyncStartStackRaw(::grpc::ClientContext* context, const ::profinet::StartRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::profinet::StartResponse, ::profinet::StartRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_StartStack_, context, request);
}

::grpc::ClientAsyncResponseReader< ::profinet::StartResponse>* ProfinetStackService::Stub::AsyncStartStackRaw(::grpc::ClientContext* context, const ::profinet::StartRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStartStackRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ProfinetStackService::Stub::StopStack(::grpc::ClientContext* context, const ::profinet::StopRequest& request, ::profinet::StopResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::profinet::StopRequest, ::profinet::StopResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_StopStack_, context, request, response);
}

void ProfinetStackService::Stub::async::StopStack(::grpc::ClientContext* context, const ::profinet::StopRequest* request, ::profinet::StopResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::profinet::StopRequest, ::profinet::StopResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StopStack_, context, request, response, std::move(f));
}

void ProfinetStackService::Stub::async::StopStack(::grpc::ClientContext* context, const ::profinet::StopRequest* request, ::profinet::StopResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StopStack_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::profinet::StopResponse>* ProfinetStackService::Stub::PrepareAsyncStopStackRaw(::grpc::ClientContext* context, const ::profinet::StopRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::profinet::StopResponse, ::profinet::StopRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_StopStack_, context, request);
}

::grpc::ClientAsyncResponseReader< ::profinet::StopResponse>* ProfinetStackService::Stub::AsyncStopStackRaw(::grpc::ClientContext* context, const ::profinet::StopRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStopStackRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReaderWriter< ::profinet::IoWriteRequest, ::profinet::IoUpdateResponse>* ProfinetStackService::Stub::StreamIoDataRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::profinet::IoWriteRequest, ::profinet::IoUpdateResponse>::Create(channel_.get(), rpcmethod_StreamIoData_, context);
}

void ProfinetStackService::Stub::async::StreamIoData(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::profinet::IoWriteRequest,::profinet::IoUpdateResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::profinet::IoWriteRequest,::profinet::IoUpdateResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamIoData_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::profinet::IoWriteRequest, ::profinet::IoUpdateResponse>* ProfinetStackService::Stub::AsyncStreamIoDataRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::profinet::IoWriteRequest, ::profinet::IoUpdateResponse>::Create(channel_.get(), cq, rpcmethod_StreamIoData_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::profinet::IoWriteRequest, ::profinet::IoUpdateResponse>* ProfinetStackService::Stub::PrepareAsyncStreamIoDataRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::profinet::IoWriteRequest, ::profinet::IoUpdateResponse>::Create(channel_.get(), cq, rpcmethod_StreamIoData_, context, false, nullptr);
}

ProfinetStackService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ProfinetStackService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ProfinetStackService::Service, ::profinet::StartRequest, ::profinet::StartResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ProfinetStackService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::profinet::StartRequest* req,
             ::profinet::StartResponse* resp) {
               return service->StartStack(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ProfinetStackService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ProfinetStackService::Service, ::profinet::StopRequest, ::profinet::StopResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ProfinetStackService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::profinet::StopRequest* req,
             ::profinet::StopResponse* resp) {
               return service->StopStack(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ProfinetStackService_method_names[2],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< ProfinetStackService::Service, ::profinet::IoWriteRequest, ::profinet::IoUpdateResponse>(
          [](ProfinetStackService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::profinet::IoUpdateResponse,
             ::profinet::IoWriteRequest>* stream) {
               return service->StreamIoData(ctx, stream);
             }, this)));
}

ProfinetStackService::Service::~Service() {
}

::grpc::Status ProfinetStackService::Service::StartStack(::grpc::ServerContext* context, const ::profinet::StartRequest* request, ::profinet::StartResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ProfinetStackService::Service::StopStack(::grpc::ServerContext* context, const ::profinet::StopRequest* request, ::profinet::StopResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ProfinetStackService::Service::StreamIoData(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::profinet::IoUpdateResponse, ::profinet::IoWriteRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace profinet
#include <grpcpp/ports_undef.inc>

