// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: profinet.proto
#ifndef GRPC_profinet_2eproto__INCLUDED
#define GRPC_profinet_2eproto__INCLUDED

#include "profinet.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace profinet {

class ProfinetStackService final {
 public:
  static constexpr char const* service_full_name() {
    return "profinet.ProfinetStackService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status StartStack(::grpc::ClientContext* context, const ::profinet::StartRequest& request, ::profinet::StartResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::profinet::StartResponse>> AsyncStartStack(::grpc::ClientContext* context, const ::profinet::StartRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::profinet::StartResponse>>(AsyncStartStackRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::profinet::StartResponse>> PrepareAsyncStartStack(::grpc::ClientContext* context, const ::profinet::StartRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::profinet::StartResponse>>(PrepareAsyncStartStackRaw(context, request, cq));
    }
    virtual ::grpc::Status StopStack(::grpc::ClientContext* context, const ::profinet::StopRequest& request, ::profinet::StopResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::profinet::StopResponse>> AsyncStopStack(::grpc::ClientContext* context, const ::profinet::StopRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::profinet::StopResponse>>(AsyncStopStackRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::profinet::StopResponse>> PrepareAsyncStopStack(::grpc::ClientContext* context, const ::profinet::StopRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::profinet::StopResponse>>(PrepareAsyncStopStackRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::profinet::IoWriteRequest, ::profinet::IoUpdateResponse>> StreamIoData(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::profinet::IoWriteRequest, ::profinet::IoUpdateResponse>>(StreamIoDataRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::profinet::IoWriteRequest, ::profinet::IoUpdateResponse>> AsyncStreamIoData(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::profinet::IoWriteRequest, ::profinet::IoUpdateResponse>>(AsyncStreamIoDataRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::profinet::IoWriteRequest, ::profinet::IoUpdateResponse>> PrepareAsyncStreamIoData(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::profinet::IoWriteRequest, ::profinet::IoUpdateResponse>>(PrepareAsyncStreamIoDataRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void StartStack(::grpc::ClientContext* context, const ::profinet::StartRequest* request, ::profinet::StartResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void StartStack(::grpc::ClientContext* context, const ::profinet::StartRequest* request, ::profinet::StartResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void StopStack(::grpc::ClientContext* context, const ::profinet::StopRequest* request, ::profinet::StopResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void StopStack(::grpc::ClientContext* context, const ::profinet::StopRequest* request, ::profinet::StopResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void StreamIoData(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::profinet::IoWriteRequest,::profinet::IoUpdateResponse>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::profinet::StartResponse>* AsyncStartStackRaw(::grpc::ClientContext* context, const ::profinet::StartRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::profinet::StartResponse>* PrepareAsyncStartStackRaw(::grpc::ClientContext* context, const ::profinet::StartRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::profinet::StopResponse>* AsyncStopStackRaw(::grpc::ClientContext* context, const ::profinet::StopRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::profinet::StopResponse>* PrepareAsyncStopStackRaw(::grpc::ClientContext* context, const ::profinet::StopRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::profinet::IoWriteRequest, ::profinet::IoUpdateResponse>* StreamIoDataRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::profinet::IoWriteRequest, ::profinet::IoUpdateResponse>* AsyncStreamIoDataRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::profinet::IoWriteRequest, ::profinet::IoUpdateResponse>* PrepareAsyncStreamIoDataRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status StartStack(::grpc::ClientContext* context, const ::profinet::StartRequest& request, ::profinet::StartResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::profinet::StartResponse>> AsyncStartStack(::grpc::ClientContext* context, const ::profinet::StartRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::profinet::StartResponse>>(AsyncStartStackRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::profinet::StartResponse>> PrepareAsyncStartStack(::grpc::ClientContext* context, const ::profinet::StartRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::profinet::StartResponse>>(PrepareAsyncStartStackRaw(context, request, cq));
    }
    ::grpc::Status StopStack(::grpc::ClientContext* context, const ::profinet::StopRequest& request, ::profinet::StopResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::profinet::StopResponse>> AsyncStopStack(::grpc::ClientContext* context, const ::profinet::StopRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::profinet::StopResponse>>(AsyncStopStackRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::profinet::StopResponse>> PrepareAsyncStopStack(::grpc::ClientContext* context, const ::profinet::StopRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::profinet::StopResponse>>(PrepareAsyncStopStackRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::profinet::IoWriteRequest, ::profinet::IoUpdateResponse>> StreamIoData(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::profinet::IoWriteRequest, ::profinet::IoUpdateResponse>>(StreamIoDataRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::profinet::IoWriteRequest, ::profinet::IoUpdateResponse>> AsyncStreamIoData(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::profinet::IoWriteRequest, ::profinet::IoUpdateResponse>>(AsyncStreamIoDataRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::profinet::IoWriteRequest, ::profinet::IoUpdateResponse>> PrepareAsyncStreamIoData(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::profinet::IoWriteRequest, ::profinet::IoUpdateResponse>>(PrepareAsyncStreamIoDataRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void StartStack(::grpc::ClientContext* context, const ::profinet::StartRequest* request, ::profinet::StartResponse* response, std::function<void(::grpc::Status)>) override;
      void StartStack(::grpc::ClientContext* context, const ::profinet::StartRequest* request, ::profinet::StartResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void StopStack(::grpc::ClientContext* context, const ::profinet::StopRequest* request, ::profinet::StopResponse* response, std::function<void(::grpc::Status)>) override;
      void StopStack(::grpc::ClientContext* context, const ::profinet::StopRequest* request, ::profinet::StopResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void StreamIoData(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::profinet::IoWriteRequest,::profinet::IoUpdateResponse>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::profinet::StartResponse>* AsyncStartStackRaw(::grpc::ClientContext* context, const ::profinet::StartRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::profinet::StartResponse>* PrepareAsyncStartStackRaw(::grpc::ClientContext* context, const ::profinet::StartRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::profinet::StopResponse>* AsyncStopStackRaw(::grpc::ClientContext* context, const ::profinet::StopRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::profinet::StopResponse>* PrepareAsyncStopStackRaw(::grpc::ClientContext* context, const ::profinet::StopRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::profinet::IoWriteRequest, ::profinet::IoUpdateResponse>* StreamIoDataRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::profinet::IoWriteRequest, ::profinet::IoUpdateResponse>* AsyncStreamIoDataRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::profinet::IoWriteRequest, ::profinet::IoUpdateResponse>* PrepareAsyncStreamIoDataRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_StartStack_;
    const ::grpc::internal::RpcMethod rpcmethod_StopStack_;
    const ::grpc::internal::RpcMethod rpcmethod_StreamIoData_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status StartStack(::grpc::ServerContext* context, const ::profinet::StartRequest* request, ::profinet::StartResponse* response);
    virtual ::grpc::Status StopStack(::grpc::ServerContext* context, const ::profinet::StopRequest* request, ::profinet::StopResponse* response);
    virtual ::grpc::Status StreamIoData(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::profinet::IoUpdateResponse, ::profinet::IoWriteRequest>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_StartStack : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StartStack() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_StartStack() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartStack(::grpc::ServerContext* /*context*/, const ::profinet::StartRequest* /*request*/, ::profinet::StartResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStartStack(::grpc::ServerContext* context, ::profinet::StartRequest* request, ::grpc::ServerAsyncResponseWriter< ::profinet::StartResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_StopStack : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StopStack() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_StopStack() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StopStack(::grpc::ServerContext* /*context*/, const ::profinet::StopRequest* /*request*/, ::profinet::StopResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStopStack(::grpc::ServerContext* context, ::profinet::StopRequest* request, ::grpc::ServerAsyncResponseWriter< ::profinet::StopResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamIoData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamIoData() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_StreamIoData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamIoData(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::profinet::IoUpdateResponse, ::profinet::IoWriteRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamIoData(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::profinet::IoUpdateResponse, ::profinet::IoWriteRequest>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(2, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_StartStack<WithAsyncMethod_StopStack<WithAsyncMethod_StreamIoData<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_StartStack : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StartStack() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::profinet::StartRequest, ::profinet::StartResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::profinet::StartRequest* request, ::profinet::StartResponse* response) { return this->StartStack(context, request, response); }));}
    void SetMessageAllocatorFor_StartStack(
        ::grpc::MessageAllocator< ::profinet::StartRequest, ::profinet::StartResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::profinet::StartRequest, ::profinet::StartResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_StartStack() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartStack(::grpc::ServerContext* /*context*/, const ::profinet::StartRequest* /*request*/, ::profinet::StartResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* StartStack(
      ::grpc::CallbackServerContext* /*context*/, const ::profinet::StartRequest* /*request*/, ::profinet::StartResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_StopStack : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StopStack() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::profinet::StopRequest, ::profinet::StopResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::profinet::StopRequest* request, ::profinet::StopResponse* response) { return this->StopStack(context, request, response); }));}
    void SetMessageAllocatorFor_StopStack(
        ::grpc::MessageAllocator< ::profinet::StopRequest, ::profinet::StopResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::profinet::StopRequest, ::profinet::StopResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_StopStack() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StopStack(::grpc::ServerContext* /*context*/, const ::profinet::StopRequest* /*request*/, ::profinet::StopResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* StopStack(
      ::grpc::CallbackServerContext* /*context*/, const ::profinet::StopRequest* /*request*/, ::profinet::StopResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_StreamIoData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamIoData() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackBidiHandler< ::profinet::IoWriteRequest, ::profinet::IoUpdateResponse>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->StreamIoData(context); }));
    }
    ~WithCallbackMethod_StreamIoData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamIoData(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::profinet::IoUpdateResponse, ::profinet::IoWriteRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::profinet::IoWriteRequest, ::profinet::IoUpdateResponse>* StreamIoData(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_StartStack<WithCallbackMethod_StopStack<WithCallbackMethod_StreamIoData<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_StartStack : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StartStack() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_StartStack() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartStack(::grpc::ServerContext* /*context*/, const ::profinet::StartRequest* /*request*/, ::profinet::StartResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_StopStack : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StopStack() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_StopStack() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StopStack(::grpc::ServerContext* /*context*/, const ::profinet::StopRequest* /*request*/, ::profinet::StopResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_StreamIoData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamIoData() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_StreamIoData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamIoData(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::profinet::IoUpdateResponse, ::profinet::IoWriteRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_StartStack : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StartStack() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_StartStack() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartStack(::grpc::ServerContext* /*context*/, const ::profinet::StartRequest* /*request*/, ::profinet::StartResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStartStack(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_StopStack : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StopStack() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_StopStack() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StopStack(::grpc::ServerContext* /*context*/, const ::profinet::StopRequest* /*request*/, ::profinet::StopResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStopStack(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamIoData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamIoData() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_StreamIoData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamIoData(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::profinet::IoUpdateResponse, ::profinet::IoWriteRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamIoData(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(2, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StartStack : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StartStack() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->StartStack(context, request, response); }));
    }
    ~WithRawCallbackMethod_StartStack() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartStack(::grpc::ServerContext* /*context*/, const ::profinet::StartRequest* /*request*/, ::profinet::StartResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* StartStack(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StopStack : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StopStack() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->StopStack(context, request, response); }));
    }
    ~WithRawCallbackMethod_StopStack() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StopStack(::grpc::ServerContext* /*context*/, const ::profinet::StopRequest* /*request*/, ::profinet::StopResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* StopStack(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamIoData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamIoData() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->StreamIoData(context); }));
    }
    ~WithRawCallbackMethod_StreamIoData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamIoData(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::profinet::IoUpdateResponse, ::profinet::IoWriteRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* StreamIoData(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_StartStack : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_StartStack() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::profinet::StartRequest, ::profinet::StartResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::profinet::StartRequest, ::profinet::StartResponse>* streamer) {
                       return this->StreamedStartStack(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_StartStack() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StartStack(::grpc::ServerContext* /*context*/, const ::profinet::StartRequest* /*request*/, ::profinet::StartResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedStartStack(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::profinet::StartRequest,::profinet::StartResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_StopStack : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_StopStack() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::profinet::StopRequest, ::profinet::StopResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::profinet::StopRequest, ::profinet::StopResponse>* streamer) {
                       return this->StreamedStopStack(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_StopStack() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StopStack(::grpc::ServerContext* /*context*/, const ::profinet::StopRequest* /*request*/, ::profinet::StopResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedStopStack(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::profinet::StopRequest,::profinet::StopResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_StartStack<WithStreamedUnaryMethod_StopStack<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_StartStack<WithStreamedUnaryMethod_StopStack<Service > > StreamedService;
};

}  // namespace profinet


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_profinet_2eproto__INCLUDED
